CREATE TABLE [B2B].[ExchangeDefinition] (
    [ItemNo]                  INT           IDENTITY (1, 1) NOT NULL,
    [DataOwnerID]             VARCHAR (20)  NULL,
    [ExchangeCode]            VARCHAR (40)  NULL,
    [SegmentName]             VARCHAR (128) NULL,
    [BaseEntityName]          VARCHAR (128) NULL,
    [SegmentEntityName]       VARCHAR (120) NULL,
    [Position]                VARCHAR (20)  NULL,
    [SegmentCode]             VARCHAR (20)  NULL,
    [SegmentRepeat]           VARCHAR (20)  NULL,
    [SegmentRequiredType]     VARCHAR (20)  NULL,
    [SegmentReference]        VARCHAR (20)  NULL,
    [DataElementID]           VARCHAR (20)  NULL,
    [DataElementType]         VARCHAR (20)  NULL,
    [DataElement]             VARCHAR (128) NULL,
    [DataElementDescription]  VARCHAR (512) NULL,
    [DataElementRequiredType] VARCHAR (20)  NULL,
    [DataType]                VARCHAR (20)  NULL,
    [MinimumLength]           SMALLINT      NULL,
    [MaximumLength]           SMALLINT      NULL,
    [Loop]                    VARCHAR (20)  NULL,
    [LoopLevel]               SMALLINT      NULL,
    [VersionID]               VARCHAR (40)  NULL,
    [UpdateSessionID]         VARCHAR (40)  NULL,
    [CreatedDateTime]         DATETIME2 (7) DEFAULT (getutcdate()) NOT NULL,
    [LastUpdateDateTime]      DATETIME2 (7) DEFAULT (getutcdate()) NOT NULL,
    [RecordStatusCode]        CHAR (1)      DEFAULT ('A') NOT NULL,
    PRIMARY KEY CLUSTERED ([ItemNo] ASC),
    CONSTRAINT [fk_ExchangeDefinitionCodeExchangeID] FOREIGN KEY ([ExchangeCode]) REFERENCES [B2B].[ExchangeCode] ([CodeID])
);

