WITH CTE AS 
(SELECT  'oracle' dbms,
        ORA_DATABASE_NAME as DB_NAME,
        t.OWNER,
        t.TABLE_NAME,
        c.COLUMN_NAME,
        c.COLUMN_ID,
        c.DATA_TYPE,
        c.DATA_LENGTH,
        decode (n.CONSTRAINT_TYPE, 'P', 'Primary Key', 'R', 'Foreign Key' ) CONSTRAINT_TYPE, --n.constraint_name,
        r.OWNER OWN,
        r.TABLE_NAME TB_NAME,
        r.COLUMN_NAME COL_NAME,
        row_number() over(partition by t.table_name, c.column_name order  by c.column_name) rownumber
        --DENSE_RANK() OVER( PARTITION BY c.column_name, c.column_id ORDER BY c.column_name) cnt
        --count(*) over (partition by c.Column_ID) as cnt
  FROM ALL_TABLES t
      LEFT JOIN ALL_TAB_COLS c
        ON t.OWNER=c.OWNER
          AND t.TABLE_NAME=c.TABLE_NAME
      LEFT JOIN ALL_CONS_COLUMNS nc
        ON c.OWNER=nc.OWNER
          AND c.TABLE_NAME=nc.TABLE_NAME
          AND c.COLUMN_NAME=nc.COLUMN_NAME
      LEFT JOIN ALL_CONSTRAINTS n
        ON nc.OWNER=n.OWNER 
          AND nc.CONSTRAINT_NAME=n.CONSTRAINT_NAME 
          AND n.CONSTRAINT_TYPE IN('P','U','R')
      LEFT JOIN ALL_CONS_COLUMNS r
        ON n.R_OWNER=r.OWNER
          AND n.R_CONSTRAINT_NAME=r.CONSTRAINT_NAME 
          AND nc.POSITION=r.POSITION 
     WHERE c.COLUMN_NAME IS NOT NULL AND T.OWNER = 'PHOENIX'
     and c.TABLE_NAME IN ('M_BUSINESS', 'M_BUSINESS_TO_BUSINESS_REL',
     'M_BUSINESS_TO_PEOPLE_RELATIONS','M_CONTACT',
     'M_PEOPLE', 'M_PROVIDER', 'M_ADJUSTER_NM',
     'M_ADDRESS', 'M_BUSINESS_HOURS','M_CPT_SERVICE_TO_PROVIDER',
     'M_CREDENTIALING_PEER_REVIEW', 'M_CREDENTIALING_CLS_REVIEW', 'M_CREDENTIALING_CONTRACT',
     'M_CREDENTIALING_LITIGATION','M_CREDENTIALING_LICENSE', 'M_CREDENTIALING', 'M_CREDENTIALING_DETAIL',
     'M_CREDENTIALING_EDUCATION', 'M_CREDENTIALING_INS_COVERAGE', 'C_GENERIC_LOOKUP', 'C_REASON',
     'C_CPT_SERVICE', 'M_ACCESS_STATUS', 'R_NOTES', 'M_OCM_LOCATION', 'M_CREDENTIALING_SPECIALTY', 'M_USER',
     'M_EQUIPMENT_PROVIDER_RELATIONS', 'M_EQUIPMENT_MODEL', 'M_EQUIPMENT_SOFTWARE', 'M_EQUIPMENT_MAKE' )
     and c.COLUMN_ID is not null
     order by t.Table_name, c.Column_ID)
     SELECT dbms, DB_NAME, OWNER, TABLE_NAME, COLUMN_NAME, COLUMN_ID, DATA_TYPE, DATA_LENGTH,
     CONSTRAINT_TYPE, --CONSTRAINT_NAME,
     OWN, TB_NAME, COL_NAME
     FROM CTE
     WHERE rownumber =1 order by Table_name, Column_ID;