-- Clinical
CREATE TABLE [Clinical].[Vaccine_Reason_Not_Given_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Vaccine_Reason_Not_Given_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Clinical].[Vaccine_Event_Source_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Vaccine_Event_Source_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Clinical].[Vaccine_Manufacturer_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Vaccine_Manufacturer_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Clinical].[Vaccine_Type] (
   [Type_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Vaccine_Type PRIMARY KEY ([Type_ID])
);

CREATE TABLE [Clinical].[Complication] (
   [Complication_ID] VARCHAR(40) NOT NULL,
   [Complication_Code_ID] VARCHAR(30),
   [Complication_Flag_ID] VARCHAR(30),
   [Acquired_DateTime] DATE,
   [Recorded_DateTime] DATE,
   [Case_ID] VARCHAR(40),
   [Subject_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Complication PRIMARY KEY ([Complication_ID])
   CONSTRAINT fk_Complication_Complication_Code_ID
      FOREIGN KEY ([Complication_Code_ID])
      REFERENCES [Clinical].[Complication_Code]([Code_ID]),
   CONSTRAINT fk_Complication_Complication_Flag_ID
      FOREIGN KEY ([Complication_Flag_ID])
      REFERENCES [Clinical].[Indicator_Flag_Code]([Code_ID]),
);

CREATE TABLE [Clinical].[Complication_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Complication_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Clinical].[Manifestation_Report] (
   [Manifestation_Report_ID] VARCHAR(40) NOT NULL,
   [Report_Date] DATE,
   [Manifestation_Date] DATE,
   [Manifestation_Code_ID] VARCHAR(30),
   [Manifestation_Flag_ID] VARCHAR(30),
   [Case_ID] VARCHAR(40),
   [Subject_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Manifestation_Report PRIMARY KEY ([Manifestation_Report_ID])
   CONSTRAINT fk_Manifestation_Report_Manifestation_Code_ID
      FOREIGN KEY ([Manifestation_Code_ID])
      REFERENCES [Clinical].[Manifestation_Code]([Code_ID]),
   CONSTRAINT fk_Manifestation_Report_Manifestation_Flag_ID
      FOREIGN KEY ([Manifestation_Flag_ID])
      REFERENCES [Clinical].[Indicator_Flag_Code]([Code_ID]),
);

CREATE TABLE [Clinical].[Manifestation_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Manifestation_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Clinical].[Medication] (
   [Medication_ID] VARCHAR(40) NOT NULL,
   [Alternate_ID] VARCHAR(40),
   [Medication_Code_ID] VARCHAR(30),
   [Dose_Form_Code_ID] VARCHAR(30),
   [Purpose_Code_ID] VARCHAR(30),
   [Prescribed_DateTime] VARCHAR(0),
   [Monitor_Medication_Flag] VARCHAR(1),
   [Monitor_DateTime] VARCHAR(0),
   [Dosage_Ordered] VARCHAR(0),
   [Dosage_Ordered_Unit_Code_ID] VARCHAR(30),
   [Dosage_Strength] VARCHAR(0),
   [Dosage_Strength_Unit_Code_ID] VARCHAR(30),
   [Measure_Unit] VARCHAR(0),
   [Measure_Unit_Code_ID] VARCHAR(30),
   [Dosage_Calculated] VARCHAR(30),
   [Frequency_Code_ID] VARCHAR(30),
   [AdditionalInstruction] VARCHAR(256),
   [Status_Code_ID] VARCHAR(30),
   [Status_DateTime] VARCHAR(0),
   [Case_ID] VARCHAR(40),
   [Subject_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Medication PRIMARY KEY ([Medication_ID])
   CONSTRAINT fk_Medication_Dose_Form_Code_ID
      FOREIGN KEY ([Dose_Form_Code_ID])
      REFERENCES [Clinical].[Dosage_Form_Code]([Code_ID]),
);

CREATE TABLE [Clinical].[Treatment] (
   [Treatment_Id] VARCHAR(40) NOT NULL,
   [Given_Indicator] BIT,
   [Name] VARCHAR(80),
   [Start_Date] VARCHAR(0),
   [End_Date] VARCHAR(0),
   [Quantity] VARCHAR(0),
   [Form] VARCHAR(30),
   [Comment] VARCHAR(4000),
   [Status_Code_ID] VARCHAR(30),
   [Status_DateTime] VARCHAR(0),
   [Activity_ID] VARCHAR(40),
   [Case_ID] VARCHAR(40),
   [Subject_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Treatment PRIMARY KEY ([Treatment_Id])
);

CREATE TABLE [Clinical].[Syndrome_Secondary_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Syndrome_Secondary_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Clinical].[Syndrome_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Syndrome_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Clinical].[Birth_Status_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Birth_Status_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Clinical].[Infant_Report] (
   [Infant_Report_ID] VARCHAR(40) NOT NULL,
   [Report_Date] DATE,
   [Birth_Weight] INT,
   [Birth_Gestational_Age] INT,
   [Birth_Status_Code_ID] VARCHAR(30),
   [Case_ID] VARCHAR(40),
   [Subject_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Infant_Report PRIMARY KEY ([Infant_Report_ID])
   CONSTRAINT fk_Infant_Report_Birth_Status_Code_ID
      FOREIGN KEY ([Birth_Status_Code_ID])
      REFERENCES [Clinical].[Birth_Status_Code]([Code_ID]),
);

CREATE TABLE [Clinical].[Symptom_Sign] (
   [Synmptom_Sign_ID] VARCHAR(40) NOT NULL,
   [Sign_Code_ID] VARCHAR(30),
   [Sign_Flag_ID] VARCHAR(30),
   [Acquired_DateTime] DATE,
   [Recorded_DateTime] DATE,
   [Case_ID] VARCHAR(40),
   [Subject_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Symptom_Sign PRIMARY KEY ([Synmptom_Sign_ID])
   CONSTRAINT fk_Symptom_Sign_Sign_Code_ID
      FOREIGN KEY ([Sign_Code_ID])
      REFERENCES [Clinical].[Symptom_Sign_Code]([Code_ID]),
   CONSTRAINT fk_Symptom_Sign_Sign_Flag_ID
      FOREIGN KEY ([Sign_Flag_ID])
      REFERENCES [Clinical].[Indicator_Flag_Code]([Code_ID]),
);

CREATE TABLE [Clinical].[Symptom_Sign_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Symptom_Sign_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Clinical].[Stage_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Stage_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Clinical].[Pregnancy_Trimester_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Pregnancy_Trimester_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Clinical].[Maternal_Report] (
   [Maternal_Report_ID] VARCHAR(40) NOT NULL,
   [Report_Date] DATE,
   [Jurisdiction_Code_ID] VARCHAR(30),
   [Pregnancies_Total] INT,
   [Births_Live_Total] INT,
   [Menstrual_Period_Last_Date] DATE,
   [Prenatal_Visit_First_Date] DATE,
   [Prenatal_Visit_Flag] VARCHAR(30),
   [Prenatal_Trimester_Code_ID] VARCHAR(30),
   [Case_ID] VARCHAR(40),
   [Subject_ID] VARCHAR(40),
   [Status_Code_ID] VARCHAR(30),
   [Status_DateTime] VARCHAR(0),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Maternal_Report PRIMARY KEY ([Maternal_Report_ID])
   CONSTRAINT fk_Maternal_Report_Prenatal_Visit_Flag
      FOREIGN KEY ([Prenatal_Visit_Flag])
      REFERENCES [Clinical].[Indicator_Flag_Code]([Code_ID]),
   CONSTRAINT fk_Maternal_Report_Prenatal_Trimester_Code_ID
      FOREIGN KEY ([Prenatal_Trimester_Code_ID])
      REFERENCES [Clinical].[Pregnancy_Trimester_Code]([Code_ID]),
);

CREATE TABLE [Clinical].[Blood_Product_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Blood_Product_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Clinical].[Blood_Transfusion_Report] (
   [Blood_Transfusion_ID] VARCHAR(40) NOT NULL,
   [Donated_Product_Code_ID] VARCHAR(30),
   [Donated_Date] DATE,
   [Donor_Flag_ID] VARCHAR(30),
   [Donor_Implicated_Flag_ID] VARCHAR(30),
   [Transfusion_Associated_Flag_ID] VARCHAR(30),
   [Transfused_Product_Code_ID] VARCHAR(30),
   [Transfused_Date] DATE,
   [Organ_Transplant_Flag_ID] VARCHAR(30),
   [Case_ID] VARCHAR(40),
   [Subject_ID] VARCHAR(40),
   [Status_Code_ID] VARCHAR(30),
   [Status_DateTime] VARCHAR(0),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Blood_Transfusion_Report PRIMARY KEY ([Blood_Transfusion_ID])
   CONSTRAINT fk_Blood_Transfusion_Report_Donated_Product_Code_ID
      FOREIGN KEY ([Donated_Product_Code_ID])
      REFERENCES [Clinical].[Blood_Product_Code]([Code_ID]),
   CONSTRAINT fk_Blood_Transfusion_Report_Donor_Flag_ID
      FOREIGN KEY ([Donor_Flag_ID])
      REFERENCES [Clinical].[Indicator_Flag_Code]([Code_ID]),
   CONSTRAINT fk_Blood_Transfusion_Report_Donor_Implicated_Flag_ID
      FOREIGN KEY ([Donor_Implicated_Flag_ID])
      REFERENCES [Clinical].[Indicator_Flag_Code]([Code_ID]),
   CONSTRAINT fk_Blood_Transfusion_Report_Transfusion_Associated_Flag_ID
      FOREIGN KEY ([Transfusion_Associated_Flag_ID])
      REFERENCES [Clinical].[Indicator_Flag_Code]([Code_ID]),
   CONSTRAINT fk_Blood_Transfusion_Report_Transfused_Product_Code_ID
      FOREIGN KEY ([Transfused_Product_Code_ID])
      REFERENCES [Clinical].[Blood_Product_Code]([Code_ID]),
   CONSTRAINT fk_Blood_Transfusion_Report_Organ_Transplant_Flag_ID
      FOREIGN KEY ([Organ_Transplant_Flag_ID])
      REFERENCES [Clinical].[Indicator_Flag_Code]([Code_ID]),
);

CREATE TABLE [Clinical].[Indicator_Flag_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Indicator_Flag_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Clinical].[Vitals] (
   [Vitals_ID] VARCHAR(40) NOT NULL,
   [Profile_Code_ID] VARCHAR(30),
   [Body_Site_Code_ID] VARCHAR(30),
   [Body_Position_Code_ID] VARCHAR(30),
   [Device_Code_ID] VARCHAR(30),
   [Method] VARCHAR(50),
   [Unit_Code_ID] VARCHAR(30),
   [Component_Code_ID] VARCHAR(30),
   [Measured_Value] VARCHAR(50),
   [Status_Code_ID] VARCHAR(30),
   [Status_DateTime] VARCHAR(0),
   [Case_ID] VARCHAR(40),
   [Subject_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Vitals PRIMARY KEY ([Vitals_ID])
   CONSTRAINT fk_Vitals_Body_Site_Code_ID
      FOREIGN KEY ([Body_Site_Code_ID])
      REFERENCES [Clinical].[Body_Site_Code]([Code_ID]),
   CONSTRAINT fk_Vitals_Body_Position_Code_ID
      FOREIGN KEY ([Body_Position_Code_ID])
      REFERENCES [Clinical].[Body_Position_Code]([Code_ID]),
   CONSTRAINT fk_Vitals_Device_Code_ID
      FOREIGN KEY ([Device_Code_ID])
      REFERENCES [Clinical].[Device_Code]([Code_ID]),
   CONSTRAINT fk_Vitals_Unit_Code_ID
      FOREIGN KEY ([Unit_Code_ID])
      REFERENCES [Clinical].[Unit_Code]([Code_ID]),
);

CREATE TABLE [Clinical].[Virus_Type] (
   [Type_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Virus_Type PRIMARY KEY ([Type_ID])
);

CREATE TABLE [Clinical].[Unit_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Unit_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Clinical].[Condition] (
   [Condition_ID] VARCHAR(40) NOT NULL,
   [Type_ID] VARCHAR(30),
   [Case_ID] VARCHAR(40),
   [Subject_ID] VARCHAR(40),
   [Qualifier_Text] VARCHAR(30),
   [Qualifier_Code_ID] VARCHAR(30),
   [Severity_Code_ID] VARCHAR(30),
   [Disease_Code_ID] VARCHAR(30),
   [Acquired_Jurisdiction_Code_ID] VARCHAR(30),
   [Acquired_Date] DATE,
   [Recorded_Date] DATE,
   [Reported_Date] DATE,
   [Diagnosis_Date] DATE,
   [Duration_Total] INT,
   [Duration_Unit_Code_ID] VARCHAR(30),
   [Body_Site_Code_ID] VARCHAR(30),
   [Body_Position_Code_ID] VARCHAR(30),
   [Stage_Clinical_Code_ID] VARCHAR(30),
   [Stage_Surveillance_Code_ID] VARCHAR(30),
   [Status_Code_ID] VARCHAR(30),
   [Status_DateTime] VARCHAR(0),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Condition PRIMARY KEY ([Condition_ID])
   CONSTRAINT fk_Condition_Disease_Code_ID
      FOREIGN KEY ([Disease_Code_ID])
      REFERENCES [Clinical].[Disease_Condition_Code]([Code_ID]),
   CONSTRAINT fk_Condition_Acquired_Jurisdiction_Code_ID
      FOREIGN KEY ([Acquired_Jurisdiction_Code_ID])
      REFERENCES [Clinical].[Jurisdiction_Code]([Code_ID]),
   CONSTRAINT fk_Condition_Duration_Unit_Code_ID
      FOREIGN KEY ([Duration_Unit_Code_ID])
      REFERENCES [Clinical].[Unit_Code]([Code_ID]),
   CONSTRAINT fk_Condition_Body_Site_Code_ID
      FOREIGN KEY ([Body_Site_Code_ID])
      REFERENCES [Clinical].[Body_Site_Code]([Code_ID]),
   CONSTRAINT fk_Condition_Body_Position_Code_ID
      FOREIGN KEY ([Body_Position_Code_ID])
      REFERENCES [Clinical].[Body_Position_Code]([Code_ID]),
   CONSTRAINT fk_Condition_Stage_Clinical_Code_ID
      FOREIGN KEY ([Stage_Clinical_Code_ID])
      REFERENCES [Clinical].[Stage_Code]([Code_ID]),
   CONSTRAINT fk_Condition_Stage_Surveillance_Code_ID
      FOREIGN KEY ([Stage_Surveillance_Code_ID])
      REFERENCES [Clinical].[Stage_Code]([Code_ID]),
);

CREATE TABLE [Clinical].[Dosage_Form_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Dosage_Form_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Clinical].[Disease_Condition_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Disease_Condition_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Clinical].[Jurisdiction_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Jurisdiction_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Clinical].[Device_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Device_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Clinical].[Body_Site_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Body_Site_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Clinical].[Body_Position_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Body_Position_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Clinical].[Immunization] (
   [Immunization_ID] VARCHAR(40) NOT NULL,
   [Type_ID] VARCHAR(30),
   [Vaccination_Record_ID] VARCHAR(40),
   [Vaccine_Type_ID] VARCHAR(30),
   [Vaccine_Manufacturer_Code_ID] VARCHAR(30),
   [Vaccine_Event_Source_Code_ID] VARCHAR(30),
   [Vaccinated_Flag_ID] VARCHAR(30),
   [Administered_DateTime] VARCHAR(0),
   [Dosage_Series_Number] VARCHAR(20),
   [Dosage_Amount] VARCHAR(50),
   [Lot_Number] VARCHAR(20),
   [Expiration_Date] VARCHAR(0),
   [Drug_Code_ID] VARCHAR(30),
   [Reason_Not_Give_Code_ID] VARCHAR(30),
   [Status_Code_ID] VARCHAR(30),
   [Status_DateTime] VARCHAR(0),
   [Activity_ID] VARCHAR(40),
   [Organization_ID] VARCHAR(40),
   [Case_ID] VARCHAR(40),
   [Subject_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Immunization PRIMARY KEY ([Immunization_ID])
   CONSTRAINT fk_Immunization_Vaccine_Type_ID
      FOREIGN KEY ([Vaccine_Type_ID])
      REFERENCES [Clinical].[Vaccine_Type]([Type_ID]),
   CONSTRAINT fk_Immunization_Vaccine_Manufacturer_Code_ID
      FOREIGN KEY ([Vaccine_Manufacturer_Code_ID])
      REFERENCES [Clinical].[Vaccine_Manufacturer_Code]([Code_ID]),
   CONSTRAINT fk_Immunization_Vaccine_Event_Source_Code_ID
      FOREIGN KEY ([Vaccine_Event_Source_Code_ID])
      REFERENCES [Clinical].[Vaccine_Event_Source_Code]([Code_ID]),
   CONSTRAINT fk_Immunization_Vaccinated_Flag_ID
      FOREIGN KEY ([Vaccinated_Flag_ID])
      REFERENCES [Clinical].[Indicator_Flag_Code]([Code_ID]),
   CONSTRAINT fk_Immunization_Reason_Not_Give_Code_ID
      FOREIGN KEY ([Reason_Not_Give_Code_ID])
      REFERENCES [Clinical].[Vaccine_Reason_Not_Given_Code]([Code_ID]),
);

CREATE TABLE [Clinical].[Finding] (
   [Finding_ID] VARCHAR(40) NOT NULL,
   [Reported_Date] DATE,
   [Finding_Code_ID] VARCHAR(30),
   [Finding_Flag_ID] VARCHAR(30),
   [Case_ID] VARCHAR(40),
   [Subject_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Finding PRIMARY KEY ([Finding_ID])
   CONSTRAINT fk_Finding_Finding_Code_ID
      FOREIGN KEY ([Finding_Code_ID])
      REFERENCES [Clinical].[Finding_Code]([Code_ID]),
   CONSTRAINT fk_Finding_Finding_Flag_ID
      FOREIGN KEY ([Finding_Flag_ID])
      REFERENCES [Clinical].[Indicator_Flag_Code]([Code_ID]),
);

CREATE TABLE [Clinical].[Finding_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Finding_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Clinical].[Risk_Factor] (
   [Risk_Factor_ID] VARCHAR(40) NOT NULL,
   [Reported_Date] DATE,
   [Factor_Code_ID] VARCHAR(30),
   [Factor_Flag_ID] VARCHAR(30),
   [Case_ID] VARCHAR(40),
   [Subject_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Risk_Factor PRIMARY KEY ([Risk_Factor_ID])
   CONSTRAINT fk_Risk_Factor_Factor_Code_ID
      FOREIGN KEY ([Factor_Code_ID])
      REFERENCES [Clinical].[Risk_Factor_Code]([Code_ID]),
   CONSTRAINT fk_Risk_Factor_Factor_Flag_ID
      FOREIGN KEY ([Factor_Flag_ID])
      REFERENCES [Clinical].[Indicator_Flag_Code]([Code_ID]),
);

CREATE TABLE [Clinical].[Risk_Factor_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Risk_Factor_Code PRIMARY KEY ([Code_ID])
);

