-- Surveillance
CREATE TABLE [Surveillance].[Complication_Report] (
   [Complication_Report_ID] VARCHAR(40) NOT NULL,
   [Report_Date] DATE,
   [Permanent_Flag_ID] VARCHAR(30),
   [Travel_Time_Last] INT,
   [Travel_Time_Unit_Code_ID] VARCHAR(30),
   [Travel_Country_Code_ID] VARCHAR(30),
   [Travel_Returned_Date] DATE,
   [Import_Status_Flag_ID] VARCHAR(30),
   [Exposure_Source_Code_ID] VARCHAR(30),
   [Detection_Method_Code_ID] VARCHAR(30),
   [Patient_Address_City_Code_ID] VARCHAR(30),
   [Investigation_Status_Code_ID] VARCHAR(30),
   [Transmission_Setting_Code_ID] VARCHAR(30),
   [Age_Setting_Verified_Flag_ID] VARCHAR(30),
   [Epidemiology_Linked_Flag_ID] VARCHAR(30),
   [Case_ID] VARCHAR(40),
   [Subject_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Complication_Report PRIMARY KEY ([Complication_Report_ID])
   CONSTRAINT fk_Complication_Report_Permanent_Flag_ID
      FOREIGN KEY ([Permanent_Flag_ID])
      REFERENCES [Surveillance].[Indicator_Flag_Code]([Code_ID]),
   CONSTRAINT fk_Complication_Report_Import_Status_Flag_ID
      FOREIGN KEY ([Import_Status_Flag_ID])
      REFERENCES [Surveillance].[Indicator_Flag_Code]([Code_ID]),
   CONSTRAINT fk_Complication_Report_Exposure_Source_Code_ID
      FOREIGN KEY ([Exposure_Source_Code_ID])
      REFERENCES [Surveillance].[Case_Classification_Exposure_Source_Code]([Code_ID]),
   CONSTRAINT fk_Complication_Report_Detection_Method_Code_ID
      FOREIGN KEY ([Detection_Method_Code_ID])
      REFERENCES [Surveillance].[Detection_Method_Code]([Code_ID]),
   CONSTRAINT fk_Complication_Report_Investigation_Status_Code_ID
      FOREIGN KEY ([Investigation_Status_Code_ID])
      REFERENCES [Surveillance].[Case_Investigation_Stattus_Code]([Code_ID]),
   CONSTRAINT fk_Complication_Report_Transmission_Setting_Code_ID
      FOREIGN KEY ([Transmission_Setting_Code_ID])
      REFERENCES [Surveillance].[Transmission_Setting_Code]([Code_ID]),
   CONSTRAINT fk_Complication_Report_Age_Setting_Verified_Flag_ID
      FOREIGN KEY ([Age_Setting_Verified_Flag_ID])
      REFERENCES [Surveillance].[Indicator_Flag_Code]([Code_ID]),
   CONSTRAINT fk_Complication_Report_Epidemiology_Linked_Flag_ID
      FOREIGN KEY ([Epidemiology_Linked_Flag_ID])
      REFERENCES [Surveillance].[Indicator_Flag_Code]([Code_ID]),
);

CREATE TABLE [Surveillance].[Reporting_Criteria_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Notifiable_Indicator] BIT,
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Reporting_Criteria_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Surveillance].[Reporting_Source_Type] (
   [Type_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Reporting_Source_Type PRIMARY KEY ([Type_ID])
);

CREATE TABLE [Surveillance].[Result_Status_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Result_Status_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Surveillance].[Case_Class_Status_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Case_Class_Status_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Surveillance].[Case_Transmission_Mode_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Case_Transmission_Mode_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Surveillance].[Exposure_Report] (
   [Exposure_Report_ID] VARCHAR(40) NOT NULL,
   [Transmission_Mode_Code_ID] VARCHAR(30),
   [Reporting_State_Code_ID] VARCHAR(30),
   [Reporting_County_Code_ID] VARCHAR(30),
   [Case_Class_Status_Code_ID] VARCHAR(30),
   [Case_Outbreak_Flag_ID] VARCHAR(30),
   [Case_Outbreak_Name_Text] VARCHAR(128),
   [Case_Investigation_Start_Date] DATE,
   [Case_Submitted_First_Date] DATE,
   [Case_Notified_CDC_Date] DATE,
   [Notify_Immediate_Flag_ID] VARCHAR(30),
   [Notification_Result_Code_ID] VARCHAR(30),
   [Jurisdiction_Code_ID] VARCHAR(30),
   [Reported_Date] DATE,
   [Reported_State_Date] DATE,
   [Reported_County_Date] DATE,
   [Reporting_Source_Type_ID] VARCHAR(30),
   [Reporting_Source_Zip_Code] VARCHAR(30),
   [Reporting_Criteria_Code_ID] VARCHAR(30),
   [Reporting_Jurisdiction_Code_ID] VARCHAR(30),
   [Person_Reporting_Name_Text] VARCHAR(128),
   [Person_Reporting_Phone_Number] VARCHAR(20),
   [Person_Reporting_Email] VARCHAR(128),
   [Comment_Text] VARCHAR(3000),
   [Case_Report_ID] VARCHAR(40),
   [Location_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Exposure_Report PRIMARY KEY ([Exposure_Report_ID])
   CONSTRAINT fk_Exposure_Report_Transmission_Mode_Code_ID
      FOREIGN KEY ([Transmission_Mode_Code_ID])
      REFERENCES [Surveillance].[Case_Transmission_Mode_Code]([Code_ID]),
   CONSTRAINT fk_Exposure_Report_Case_Class_Status_Code_ID
      FOREIGN KEY ([Case_Class_Status_Code_ID])
      REFERENCES [Surveillance].[Case_Class_Status_Code]([Code_ID]),
   CONSTRAINT fk_Exposure_Report_Case_Outbreak_Flag_ID
      FOREIGN KEY ([Case_Outbreak_Flag_ID])
      REFERENCES [Surveillance].[Indicator_Flag_Code]([Code_ID]),
   CONSTRAINT fk_Exposure_Report_Notify_Immediate_Flag_ID
      FOREIGN KEY ([Notify_Immediate_Flag_ID])
      REFERENCES [Surveillance].[Indicator_Flag_Code]([Code_ID]),
   CONSTRAINT fk_Exposure_Report_Notification_Result_Code_ID
      FOREIGN KEY ([Notification_Result_Code_ID])
      REFERENCES [Surveillance].[Result_Status_Code]([Code_ID]),
   CONSTRAINT fk_Exposure_Report_Reporting_Source_Type_ID
      FOREIGN KEY ([Reporting_Source_Type_ID])
      REFERENCES [Surveillance].[Reporting_Source_Type]([Type_ID]),
   CONSTRAINT fk_Exposure_Report_Reporting_Criteria_Code_ID
      FOREIGN KEY ([Reporting_Criteria_Code_ID])
      REFERENCES [Surveillance].[Reporting_Criteria_Code]([Code_ID]),
   CONSTRAINT fk_Exposure_Report_Case_Report_ID
      FOREIGN KEY ([Case_Report_ID])
      REFERENCES [Surveillance].[Case_Report]([Case_Report_ID]),
);

CREATE TABLE [Surveillance].[Profile_Type] (
   [Type_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Profile_Type PRIMARY KEY ([Type_ID])
);

CREATE TABLE [Surveillance].[Assessment_Type] (
   [Type_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Assessment_Type PRIMARY KEY ([Type_ID])
);

CREATE TABLE [Surveillance].[Travel_Detail] (
   [Travel_Detail_ID] VARCHAR(40) NOT NULL,
   [Travel_Parent_ID] VARCHAR(40),
   [Type_ID] VARCHAR(20),
   [Purpose_Code_ID] VARCHAR(30),
   [Case_ID] VARCHAR(40),
   [Subject_ID] VARCHAR(40),
   [Travel_Number] VARCHAR(20),
   [State_Code_ID] VARCHAR(30),
   [County_Code_ID] VARCHAR(30),
   [Country_Code_ID] VARCHAR(30),
   [Origin_ID] VARCHAR(20),
   [Destination_ID] VARCHAR(20),
   [Departure_DateTime] VARCHAR(0),
   [Arrival_DateTime] VARCHAR(0),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Travel_Detail PRIMARY KEY ([Travel_Detail_ID])
   CONSTRAINT fk_Travel_Detail_Purpose_Code_ID
      FOREIGN KEY ([Purpose_Code_ID])
      REFERENCES [Surveillance].[Travel_Purpose_Code]([Code_ID]),
);

CREATE TABLE [Surveillance].[Profile_Condition] (
   [Profile_Condition_ID] VARCHAR(40) NOT NULL,
   [Profile_ID] VARCHAR(40),
   [Condition_Code_ID] VARCHAR(30),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Profile_Condition PRIMARY KEY ([Profile_Condition_ID])
   CONSTRAINT fk_Profile_Condition_Profile_ID
      FOREIGN KEY ([Profile_ID])
      REFERENCES [Surveillance].[Profile]([Profile_ID]),
);

CREATE TABLE [Surveillance].[Profile] (
   [Profile_ID] VARCHAR(40) NOT NULL,
   [Profile_Type_ID] VARCHAR(30),
   [Profile_Name] VARCHAR(80),
   [Status_Code_ID] VARCHAR(30),
   [Status_DateTime] VARCHAR(0),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Profile PRIMARY KEY ([Profile_ID])
   CONSTRAINT fk_Profile_Profile_Type_ID
      FOREIGN KEY ([Profile_Type_ID])
      REFERENCES [Surveillance].[Profile_Type]([Type_ID]),
);

CREATE TABLE [Surveillance].[Assessment_Questionnaire] (
   [Questionnaire_ID] VARCHAR(40) NOT NULL,
   [Questionnaire_No] INT,
   [Title] VARCHAR(256),
   [Description] VARCHAR(256),
   [Questionnaire_URL] VARCHAR(256),
   [Questionnaire_Answer_URL] VARCHAR(256),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Assessment_Questionnaire PRIMARY KEY ([Questionnaire_ID])
);

CREATE TABLE [Surveillance].[Assessment_Question] (
   [Question_ID] VARCHAR(40) NOT NULL,
   [Question_Sequence] INT,
   [Question_Text] VARCHAR(512),
   [Questionnaire_ID] VARCHAR(40),
   [Answer_Type_ID] VARCHAR(30),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Assessment_Question PRIMARY KEY ([Question_ID])
   CONSTRAINT fk_Assessment_Question_Questionnaire_ID
      FOREIGN KEY ([Questionnaire_ID])
      REFERENCES [Surveillance].[Assessment_Questionnaire]([Questionnaire_ID]),
   CONSTRAINT fk_Assessment_Question_Answer_Type_ID
      FOREIGN KEY ([Answer_Type_ID])
      REFERENCES [Surveillance].[Answer_Type]([Type_ID]),
);

CREATE TABLE [Surveillance].[Assessment_Answer] (
   [Answer_ID] VARCHAR(40) NOT NULL,
   [Assessment_ID] VARCHAR(40),
   [Question_ID] VARCHAR(40),
   [AnswerValue] VARCHAR(256),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Assessment_Answer PRIMARY KEY ([Answer_ID])
   CONSTRAINT fk_Assessment_Answer_Assessment_ID
      FOREIGN KEY ([Assessment_ID])
      REFERENCES [Surveillance].[Assessment]([Assessment_ID]),
   CONSTRAINT fk_Assessment_Answer_Question_ID
      FOREIGN KEY ([Question_ID])
      REFERENCES [Surveillance].[Assessment_Question]([Question_ID]),
);

CREATE TABLE [Surveillance].[Assessment] (
   [Assessment_ID] VARCHAR(40) NOT NULL,
   [Type_ID] VARCHAR(30),
   [Alternate_ID] VARCHAR(40),
   [Description] VARCHAR(1024),
   [Questionnaire_ID] VARCHAR(40),
   [Case_ID] VARCHAR(40),
   [Subject_ID] VARCHAR(40),
   [Status_Code_ID] VARCHAR(30),
   [Status_DateTime] VARCHAR(0),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Assessment PRIMARY KEY ([Assessment_ID])
   CONSTRAINT fk_Assessment_Type_ID
      FOREIGN KEY ([Type_ID])
      REFERENCES [Surveillance].[Assessment_Type]([Type_ID]),
   CONSTRAINT fk_Assessment_Questionnaire_ID
      FOREIGN KEY ([Questionnaire_ID])
      REFERENCES [Surveillance].[Assessment_Questionnaire]([Questionnaire_ID]),
);

CREATE TABLE [Surveillance].[Answer_Type] (
   [Type_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Status_Code_ID] VARCHAR(30),
   [Status_DateTime] VARCHAR(0),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Answer_Type PRIMARY KEY ([Type_ID])
);

CREATE TABLE [Surveillance].[Report_Type] (
   [Type_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Status_Code_ID] VARCHAR(30),
   [Status_DateTime] VARCHAR(0),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Report_Type PRIMARY KEY ([Type_ID])
);

CREATE TABLE [Surveillance].[Case_Report] (
   [Case_Report_ID] VARCHAR(40) NOT NULL,
   [Report_Date] DATE,
   [Type_ID] VARCHAR(30),
   [Description] VARCHAR(1024),
   [Illness_Onset_Date] DATE,
   [Illness_End_Date] DATE,
   [Illness_Duration] INT,
   [Illness_Duration_Unit_Code_ID] VARCHAR(30),
   [Pregnancy_Status_Flag_ID] VARCHAR(30),
   [Diagnosis_Date] DATE,
   [Hospitalized_Flag_ID] VARCHAR(30),
   [Hospital_Stay_InDays] INT,
   [Admission_Date] DATE,
   [Discharged_Date] DATE,
   [Exposure_Setting_Code_ID] VARCHAR(30),
   [Condition_Code_ID] VARCHAR(30),
   [Subject_Died_Flag_ID] VARCHAR(30),
   [Deceased_Date] DATE,
   [Deceased_Source_Code_ID] VARCHAR(30),
   [Imported_Country_Code_ID] VARCHAR(30),
   [Imported_State_Code_ID] VARCHAR(30),
   [Imported_City_Code_ID] VARCHAR(30),
   [Imported_County_Code_ID] VARCHAR(30),
   [Age_At_Case] INT,
   [Age_Unit_Code_ID] VARCHAR(30),
   [Case_State_ID] VARCHAR(40),
   [Case_Legacy_ID] VARCHAR(40),
   [Case_ID] VARCHAR(40),
   [Subject_ID] VARCHAR(40),
   [Status_Code_ID] VARCHAR(30),
   [Status_DateTime] VARCHAR(0),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Case_Report PRIMARY KEY ([Case_Report_ID])
   CONSTRAINT fk_Case_Report_Type_ID
      FOREIGN KEY ([Type_ID])
      REFERENCES [Surveillance].[Report_Type]([Type_ID]),
   CONSTRAINT fk_Case_Report_Illness_Duration_Unit_Code_ID
      FOREIGN KEY ([Illness_Duration_Unit_Code_ID])
      REFERENCES [Surveillance].[Unit_Code]([Code_ID]),
   CONSTRAINT fk_Case_Report_Pregnancy_Status_Flag_ID
      FOREIGN KEY ([Pregnancy_Status_Flag_ID])
      REFERENCES [Surveillance].[Indicator_Flag_Code]([Code_ID]),
   CONSTRAINT fk_Case_Report_Hospitalized_Flag_ID
      FOREIGN KEY ([Hospitalized_Flag_ID])
      REFERENCES [Surveillance].[Indicator_Flag_Code]([Code_ID]),
   CONSTRAINT fk_Case_Report_Exposure_Setting_Code_ID
      FOREIGN KEY ([Exposure_Setting_Code_ID])
      REFERENCES [Surveillance].[Exposure_Setting_Code]([Code_ID]),
   CONSTRAINT fk_Case_Report_Subject_Died_Flag_ID
      FOREIGN KEY ([Subject_Died_Flag_ID])
      REFERENCES [Surveillance].[Indicator_Flag_Code]([Code_ID]),
   CONSTRAINT fk_Case_Report_Deceased_Source_Code_ID
      FOREIGN KEY ([Deceased_Source_Code_ID])
      REFERENCES [Surveillance].[Jurisdiction_Code]([Code_ID]),
);

CREATE TABLE [Surveillance].[Travel_Purpose_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Travel_Purpose_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Surveillance].[Exposure_Location_Report] (
   [Exposure_Report_ID] VARCHAR(40) NOT NULL,
   [Country_Code_ID] VARCHAR(30),
   [State_Code_ID] VARCHAR(30),
   [City_Code_ID] VARCHAR(30),
   [County_Code_ID] VARCHAR(30),
   [Case_Report_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Exposure_Location_Report PRIMARY KEY ([Exposure_Report_ID])
   CONSTRAINT fk_Exposure_Location_Report_Case_Report_ID
      FOREIGN KEY ([Case_Report_ID])
      REFERENCES [Surveillance].[Case_Report]([Case_Report_ID]),
);

CREATE TABLE [Surveillance].[Jurisdiction_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Jurisdiction_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Surveillance].[Unit_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Unit_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Surveillance].[Event_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Notifiable_Indicator] BIT,
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Event_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Surveillance].[Sexual_Preference_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Sexual_Preference_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Surveillance].[Indicator_Flag_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Indicator_Flag_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Surveillance].[Contact_Type] (
   [Type_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Contact_Type PRIMARY KEY ([Type_ID])
);

CREATE TABLE [Surveillance].[Contact_Report] (
   [Contact_Report_ID] VARCHAR(40) NOT NULL,
   [Report_Date] DATE,
   [Contacted_Date] DATE,
   [Contact_Type_ID] VARCHAR(30),
   [Contact_Type_Other_Flag_ID] VARCHAR(30),
   [Contact_Type_Other_Text] VARCHAR(128),
   [Contact_Flag_ID] VARCHAR(30),
   [Epidemiology_Linked_Flag_ID] VARCHAR(30),
   [Case_Linked_Flag_ID] VARCHAR(30),
   [Child_Care_Linked_Flag_ID] VARCHAR(30),
   [Child_Care_Case_Flag_ID] VARCHAR(30),
   [Sexual_Preference_Code_ID] VARCHAR(30),
   [Sexual_Partner_Male_Total] INT,
   [Sexual_Partner_Female_Total] INT,
   [Drug_Used_Flag_ID] VARCHAR(30),
   [Drug_Street_Used_Flag_ID] VARCHAR(30),
   [Traveled_Flag_ID] VARCHAR(30),
   [Travel_Detail_ID] VARCHAR(40),
   [Outbreak_Source_Flag_ID] VARCHAR(30),
   [Outbreak_Foodborne_Flag_ID] VARCHAR(30),
   [Outbreak_Food_Item_Text] VARCHAR(128),
   [Outbreak_Waterborne_Flag_ID] VARCHAR(30),
   [Outbreak_Unidentified_Flag_ID] VARCHAR(30),
   [Food_Handler_Flag_ID] VARCHAR(30),
   [Case_ID] VARCHAR(40),
   [Subject_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Contact_Report PRIMARY KEY ([Contact_Report_ID])
   CONSTRAINT fk_Contact_Report_Contact_Type_ID
      FOREIGN KEY ([Contact_Type_ID])
      REFERENCES [Surveillance].[Contact_Type]([Type_ID]),
   CONSTRAINT fk_Contact_Report_Contact_Type_Other_Flag_ID
      FOREIGN KEY ([Contact_Type_Other_Flag_ID])
      REFERENCES [Surveillance].[Indicator_Flag_Code]([Code_ID]),
   CONSTRAINT fk_Contact_Report_Contact_Flag_ID
      FOREIGN KEY ([Contact_Flag_ID])
      REFERENCES [Surveillance].[Indicator_Flag_Code]([Code_ID]),
   CONSTRAINT fk_Contact_Report_Epidemiology_Linked_Flag_ID
      FOREIGN KEY ([Epidemiology_Linked_Flag_ID])
      REFERENCES [Surveillance].[Indicator_Flag_Code]([Code_ID]),
   CONSTRAINT fk_Contact_Report_Case_Linked_Flag_ID
      FOREIGN KEY ([Case_Linked_Flag_ID])
      REFERENCES [Surveillance].[Indicator_Flag_Code]([Code_ID]),
   CONSTRAINT fk_Contact_Report_Child_Care_Linked_Flag_ID
      FOREIGN KEY ([Child_Care_Linked_Flag_ID])
      REFERENCES [Surveillance].[Indicator_Flag_Code]([Code_ID]),
   CONSTRAINT fk_Contact_Report_Child_Care_Case_Flag_ID
      FOREIGN KEY ([Child_Care_Case_Flag_ID])
      REFERENCES [Surveillance].[Indicator_Flag_Code]([Code_ID]),
   CONSTRAINT fk_Contact_Report_Sexual_Preference_Code_ID
      FOREIGN KEY ([Sexual_Preference_Code_ID])
      REFERENCES [Surveillance].[Sexual_Preference_Code]([Code_ID]),
   CONSTRAINT fk_Contact_Report_Drug_Used_Flag_ID
      FOREIGN KEY ([Drug_Used_Flag_ID])
      REFERENCES [Surveillance].[Indicator_Flag_Code]([Code_ID]),
   CONSTRAINT fk_Contact_Report_Drug_Street_Used_Flag_ID
      FOREIGN KEY ([Drug_Street_Used_Flag_ID])
      REFERENCES [Surveillance].[Indicator_Flag_Code]([Code_ID]),
   CONSTRAINT fk_Contact_Report_Traveled_Flag_ID
      FOREIGN KEY ([Traveled_Flag_ID])
      REFERENCES [Surveillance].[Indicator_Flag_Code]([Code_ID]),
   CONSTRAINT fk_Contact_Report_Outbreak_Source_Flag_ID
      FOREIGN KEY ([Outbreak_Source_Flag_ID])
      REFERENCES [Surveillance].[Indicator_Flag_Code]([Code_ID]),
   CONSTRAINT fk_Contact_Report_Outbreak_Foodborne_Flag_ID
      FOREIGN KEY ([Outbreak_Foodborne_Flag_ID])
      REFERENCES [Surveillance].[Indicator_Flag_Code]([Code_ID]),
   CONSTRAINT fk_Contact_Report_Outbreak_Waterborne_Flag_ID
      FOREIGN KEY ([Outbreak_Waterborne_Flag_ID])
      REFERENCES [Surveillance].[Indicator_Flag_Code]([Code_ID]),
   CONSTRAINT fk_Contact_Report_Outbreak_Unidentified_Flag_ID
      FOREIGN KEY ([Outbreak_Unidentified_Flag_ID])
      REFERENCES [Surveillance].[Indicator_Flag_Code]([Code_ID]),
   CONSTRAINT fk_Contact_Report_Food_Handler_Flag_ID
      FOREIGN KEY ([Food_Handler_Flag_ID])
      REFERENCES [Surveillance].[Indicator_Flag_Code]([Code_ID]),
);

CREATE TABLE [Surveillance].[Exposure_Setting_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Exposure_Setting_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Surveillance].[Viral_Report] (
   [Viral_Report_ID] VARCHAR(40) NOT NULL,
   [Report_Date] DATE,
   [Status_Code_ID] VARCHAR(30),
   [Status_DateTime] VARCHAR(0),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Viral_Report PRIMARY KEY ([Viral_Report_ID])
);

CREATE TABLE [Surveillance].[Transmission_Setting_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Transmission_Setting_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Surveillance].[Detection_Method_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Detection_Method_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Surveillance].[Case_Investigation_Stattus_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Case_Investigation_Stattus_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Surveillance].[Case_Classification_Exposure_Source_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Case_Classification_Exposure_Source_Code PRIMARY KEY ([Code_ID])
);

