-- Message
CREATE TABLE [Message].[Content_Type] (
   [Type_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(80),
   [Local_Type_ID] VARCHAR(30),
   [Regional_Type_ID] VARCHAR(30),
   [Source_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Content_Type PRIMARY KEY ([Type_ID])
);

CREATE TABLE [Message].[Submission] (
   [Submission_ID] VARCHAR(40) NOT NULL,
   [Submission_DateTime] VARCHAR(0),
   [Reference_ID] VARCHAR(40),
   [Received_DateTime] VARCHAR(0),
   [Message_DateTime] VARCHAR(0),
   [Data_Item_ID] VARCHAR(50),
   [Content_Type_ID] VARCHAR(30),
   [Content_ID] VARCHAR(40),
   [Source_ID] VARCHAR(40),
   [Source_Local_ID] VARCHAR(40),
   [Message_Data] VARCHAR(MAX),
   [Message_Count] INT,
   [Message_Length_InBytes] INT,
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Submission PRIMARY KEY ([Submission_ID])
   CONSTRAINT fk_Submission_Content_Type_ID
      FOREIGN KEY ([Content_Type_ID])
      REFERENCES [Message].[Content_Type]([Type_ID]),
);

