-- Generic
CREATE TABLE [Generic].[Entity_Type] (
   [Type_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Version_Number] VARCHAR(20),
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Sequence_Number] INT,
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Entity_Type PRIMARY KEY ([Type_ID])
);

CREATE TABLE [Generic].[Entity] (
   [Entity_ID] VARCHAR(40) NOT NULL,
   [Type_ID] VARCHAR(30),
   [Description] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Entity PRIMARY KEY ([Entity_ID])
   CONSTRAINT fk_Entity_Type_ID
      FOREIGN KEY ([Type_ID])
      REFERENCES [Generic].[Entity_Type]([Type_ID]),
);

CREATE TABLE [Generic].[Element_Value_Type] (
   [Type_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(80),
   [Category_ID] VARCHAR(30),
   [Tags] VARCHAR(128),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Element_Value_Type PRIMARY KEY ([Type_ID])
);

CREATE TABLE [Generic].[Element_Value] (
   [Element_Value_ID] VARCHAR(40) NOT NULL,
   [Element_ID] VARCHAR(40),
   [Type_ID] VARCHAR(30),
   [Sequence_No] INT,
   [Reference_Date] DATE,
   [Reference_Time] VARCHAR(0),
   [Entity_Type_ID] VARCHAR(30),
   [Entity_ID] VARCHAR(40),
   [Checked] BIT,
   [Start_Date] DATE,
   [End_Date] DATE,
   [Start_Value] VARCHAR(0),
   [End_Value] VARCHAR(0),
   [Value_Numeric] VARCHAR(0),
   [Value_Text] VARCHAR(128),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Element_Value PRIMARY KEY ([Element_Value_ID])
   CONSTRAINT fk_Element_Value_Element_ID
      FOREIGN KEY ([Element_ID])
      REFERENCES [Generic].[Element]([Element_ID]),
   CONSTRAINT fk_Element_Value_Type_ID
      FOREIGN KEY ([Type_ID])
      REFERENCES [Generic].[Element_Value_Type]([Type_ID]),
   CONSTRAINT fk_Element_Value_Entity_Type_ID
      FOREIGN KEY ([Entity_Type_ID])
      REFERENCES [Entity].[Entity_Type]([Type_ID]),
);

CREATE TABLE [Generic].[Element] (
   [Element_ID] VARCHAR(40) NOT NULL,
   [Group_ID] VARCHAR(40),
   [Label_Text] VARCHAR(128),
   [Sequence_No] INT,
   [Period_To_Comply] VARCHAR(30),
   [Required_Code_ID] VARCHAR(30),
   [Value_Type_ID] VARCHAR(30),
   [Code_Type_ID] VARCHAR(30),
   [Checked] BIT,
   [Start_Date] DATE,
   [End_Date] DATE,
   [Start_Value] VARCHAR(0),
   [End_Value] VARCHAR(0),
   [Value_Numeric] VARCHAR(0),
   [Value_Text] VARCHAR(128),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Element PRIMARY KEY ([Element_ID])
   CONSTRAINT fk_Element_Group_ID
      FOREIGN KEY ([Group_ID])
      REFERENCES [Generic].[Entity]([Entity_ID]),
   CONSTRAINT fk_Element_Value_Type_ID
      FOREIGN KEY ([Value_Type_ID])
      REFERENCES [Generic].[Element_Value_Type]([Type_ID]),
);

