-- Action
CREATE TABLE [Action].[Media] (
   [Activity_ID] VARCHAR(40),
   [Event_ID] VARCHAR(40),
   [Media_ID] VARCHAR(40) NOT NULL,
   [Alternate_ID] VARCHAR(80),
   [Type_ID] VARCHAR(30),
   [Category_Text] VARCHAR(80),
   [Status_Code] INT,
   [Url_Text] VARCHAR(1024),
   [Size_In_Bytes] INT,
   [Media_Data] VARCHAR(MAX),
   [Scope_Code_ID] VARCHAR(30),
   [Content_Type_Code_ID] VARCHAR(30),
   [Content_Type_Text] VARCHAR(128),
   [Default_Indicator] BIT,
   [Serial_No] BIGINT,
   [Status_Code_ID] VARCHAR(30),
   [Status_DateTime] VARCHAR(0),
   [Reference_Date_Type_ID] VARCHAR(30),
   [Reference_DateTime] VARCHAR(0),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Media PRIMARY KEY ([Media_ID])
   CONSTRAINT fk_Media_Activity_ID
      FOREIGN KEY ([Activity_ID])
      REFERENCES [Action].[Activity]([Activity_ID]),
   CONSTRAINT fk_Media_Event_ID
      FOREIGN KEY ([Event_ID])
      REFERENCES [Action].[Event]([Event_ID]),
   CONSTRAINT fk_Media_Type_ID
      FOREIGN KEY ([Type_ID])
      REFERENCES [Action].[Media_Type]([Type_ID]),
);

CREATE TABLE [Action].[Role_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Role_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Action].[Party_Type] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Party_Type PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Action].[Party] (
   [Party_ID] VARCHAR(40) NOT NULL,
   [Type_ID] VARCHAR(30),
   [Identification_ID] VARCHAR(80),
   [Role_Code_ID] VARCHAR(30),
   [Duration] VARCHAR(50),
   [Activity_ID] VARCHAR(40),
   [Organization_ID] VARCHAR(40),
   [Contact_ID] VARCHAR(40),
   [Person_ID] VARCHAR(40),
   [Status_Code_ID] VARCHAR(30),
   [Status_DateTime] VARCHAR(0),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Party PRIMARY KEY ([Party_ID])
   CONSTRAINT fk_Party_Type_ID
      FOREIGN KEY ([Type_ID])
      REFERENCES [Action].[Party_Type]([Code_ID]),
   CONSTRAINT fk_Party_Role_Code_ID
      FOREIGN KEY ([Role_Code_ID])
      REFERENCES [Action].[Role_Code]([Code_ID]),
   CONSTRAINT fk_Party_Activity_ID
      FOREIGN KEY ([Activity_ID])
      REFERENCES [Action].[Activity]([Activity_ID]),
);

CREATE TABLE [Action].[Activity] (
   [Activity_ID] VARCHAR(40) NOT NULL,
   [Alternate_ID] VARCHAR(40),
   [Type_ID] VARCHAR(30),
   [Disposition_ID] VARCHAR(40),
   [Name] VARCHAR(80),
   [Description] VARCHAR(256),
   [Priority_Code_ID] VARCHAR(30),
   [Reason_Code_ID] VARCHAR(30),
   [Scheduled_DateTime] VARCHAR(0),
   [Started_DateTime] VARCHAR(0),
   [Ended_DateTime] VARCHAR(0),
   [Status_Code_ID] VARCHAR(30),
   [Status_DateTime] VARCHAR(0),
   [Case_ID] VARCHAR(40),
   [Location_ID] VARCHAR(40),
   [Contact_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Activity PRIMARY KEY ([Activity_ID])
   CONSTRAINT fk_Activity_Type_ID
      FOREIGN KEY ([Type_ID])
      REFERENCES [Action].[Activity_Type]([Type_ID]),
   CONSTRAINT fk_Activity_Disposition_ID
      FOREIGN KEY ([Disposition_ID])
      REFERENCES [Action].[Disposition]([Disposition_ID]),
   CONSTRAINT fk_Activity_Priority_Code_ID
      FOREIGN KEY ([Priority_Code_ID])
      REFERENCES [Action].[Priority_Code]([Code_ID]),
   CONSTRAINT fk_Activity_Reason_Code_ID
      FOREIGN KEY ([Reason_Code_ID])
      REFERENCES [Action].[Reason_Code]([Code_ID]),
);

CREATE TABLE [Action].[Schedule_Event] (
   [Schedule_Event_ID] VARCHAR(40) NOT NULL,
   [Type_ID] VARCHAR(30),
   [Activity_ID] VARCHAR(40),
   [Disposition_ID] VARCHAR(40),
   [Name] VARCHAR(80),
   [Description] VARCHAR(256),
   [Priority_Code_ID] VARCHAR(30),
   [Reason_Code_ID] VARCHAR(30),
   [Scheduled_DateTime] VARCHAR(0),
   [Started_DateTime] VARCHAR(0),
   [Ended_DateTime] VARCHAR(0),
   [Status_Code_ID] VARCHAR(30),
   [Status_DateTime] VARCHAR(0),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Schedule_Event PRIMARY KEY ([Schedule_Event_ID])
   CONSTRAINT fk_Schedule_Event_Type_ID
      FOREIGN KEY ([Type_ID])
      REFERENCES [Action].[Activity_Type]([Type_ID]),
   CONSTRAINT fk_Schedule_Event_Activity_ID
      FOREIGN KEY ([Activity_ID])
      REFERENCES [Action].[Activity]([Activity_ID]),
   CONSTRAINT fk_Schedule_Event_Disposition_ID
      FOREIGN KEY ([Disposition_ID])
      REFERENCES [Action].[Disposition]([Disposition_ID]),
   CONSTRAINT fk_Schedule_Event_Priority_Code_ID
      FOREIGN KEY ([Priority_Code_ID])
      REFERENCES [Action].[Priority_Code]([Code_ID]),
   CONSTRAINT fk_Schedule_Event_Reason_Code_ID
      FOREIGN KEY ([Reason_Code_ID])
      REFERENCES [Action].[Reason_Code]([Code_ID]),
);

CREATE TABLE [Action].[Note_Type] (
   [Type_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(80),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Note_Type PRIMARY KEY ([Type_ID])
);

CREATE TABLE [Action].[Note] (
   [Note_ID] VARCHAR(40) NOT NULL,
   [Note_Type_ID] VARCHAR(30),
   [Note_Text] VARCHAR(4096),
   [Note_DateTime] VARCHAR(0),
   [Author_ID] VARCHAR(40),
   [Author_Role_ID] VARCHAR(30),
   [Author_Name] VARCHAR(80),
   [Status_Code_ID] VARCHAR(30),
   [Status_DateTime] VARCHAR(0),
   [Activity_ID] VARCHAR(40),
   [Event_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Note PRIMARY KEY ([Note_ID])
   CONSTRAINT fk_Note_Note_Type_ID
      FOREIGN KEY ([Note_Type_ID])
      REFERENCES [Action].[Note_Type]([Type_ID]),
   CONSTRAINT fk_Note_Activity_ID
      FOREIGN KEY ([Activity_ID])
      REFERENCES [Action].[Activity]([Activity_ID]),
   CONSTRAINT fk_Note_Event_ID
      FOREIGN KEY ([Event_ID])
      REFERENCES [Action].[Event]([Event_ID]),
);

CREATE TABLE [Action].[Media_Type] (
   [Type_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(80),
   [Category_ID] VARCHAR(30),
   [Tags] VARCHAR(128),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Media_Type PRIMARY KEY ([Type_ID])
);

CREATE TABLE [Action].[Disposition_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Disposition_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Action].[Event] (
   [Event_ID] VARCHAR(40) NOT NULL,
   [Alternate_ID] VARCHAR(40),
   [Activity_ID] VARCHAR(40),
   [EventType_ID] VARCHAR(20),
   [Description] VARCHAR(256),
   [Organization_ID] VARCHAR(40),
   [Person_ID] VARCHAR(40),
   [Scheduled_DateTime] VARCHAR(0),
   [Started_DateTime] VARCHAR(0),
   [Ended_DateTime] VARCHAR(0),
   [Status_Code_ID] VARCHAR(30),
   [Status_DateTime] VARCHAR(0),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Event PRIMARY KEY ([Event_ID])
   CONSTRAINT fk_Event_Activity_ID
      FOREIGN KEY ([Activity_ID])
      REFERENCES [Action].[Activity]([Activity_ID]),
);

CREATE TABLE [Action].[Activity_Type] (
   [Type_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Activity_Type PRIMARY KEY ([Type_ID])
);

CREATE TABLE [Action].[Reason_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Reason_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Action].[Priority_Code] (
   [Code_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Priority_Code PRIMARY KEY ([Code_ID])
);

CREATE TABLE [Action].[Disposition] (
   [Disposition_ID] VARCHAR(40) NOT NULL,
   [Code_ID] VARCHAR(30),
   [Status_Code_ID] VARCHAR(30),
   [Status_DateTime] VARCHAR(0),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Disposition PRIMARY KEY ([Disposition_ID])
);

