-- Article
CREATE TABLE [Article].[Item] (
   [Item_ID] VARCHAR(40) NOT NULL,
   [Name] VARCHAR(50),
   [Type_ID] VARCHAR(30),
   [Value_Amount] VARCHAR(0),
   [Quantity] VARCHAR(0),
   [Status_Code_ID] VARCHAR(30),
   [Status_DateTime] VARCHAR(0),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Item PRIMARY KEY ([Item_ID])
   CONSTRAINT fk_Item_Type_ID
      FOREIGN KEY ([Type_ID])
      REFERENCES [Article].[Item_Type]([Type_ID]),
);

CREATE TABLE [Article].[Item_Type] (
   [Type_ID] VARCHAR(30) NOT NULL,
   [Description] VARCHAR(128),
   [Category_ID] VARCHAR(30),
   [CodeSet_Name] VARCHAR(80),
   [Tenant_ID] VARCHAR(40),
   [Data_Owner_ID] VARCHAR(40),
   [Agency_Reporting_ID] VARCHAR(40),
   [Sequence_Number] INT,
   [Effective_DateTime] VARCHAR(0),
   [Effective_End_DateTime] VARCHAR(0),
   [Version_Number] VARCHAR(20),
   [Created_DateTime] VARCHAR(0),
   [Updated_DateTime] VARCHAR(0),
   [Record_Status_Code_ID] VARCHAR(1),
   [Session_Updated_ID] VARCHAR(40),
   [Tenant_ID] VARCHAR(40) NOT NULL,
   [Data_Owner_ID] VARCHAR(40) NOT NULL,
   [Agency_Reporting_ID] VARCHAR(40) NOT NULL,
   [Sequence_Number] INTEGER NOT NULL,
   [Effective_DateTime] DATETIME(getutcdate()) NOT NULL,
   [Effective_End_DateTime] DATETIME NOT NULL,
   [Version_Number] VARCHAR(20) NOT NULL,
   [Created_DateTime] DATETIME NOT NULL,
   [Updated_DateTime] DATETIME NOT NULL,
   [Record_Status_Code_ID] CHAR(1) NOT NULL,
   [Session_Updated_ID] VARCHAR(40) NOT NULL,
   CONSTRAINT pk_Item_Type PRIMARY KEY ([Type_ID])
);

